CREATE TABLE T_GEOMOTTU_MOTO (
    id_moto BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    nr_placa VARCHAR(8) UNIQUE,
    nr_chassi VARCHAR(50) UNIQUE,
    tp_modelo VARCHAR(255) NOT NULL,
    st_operacional VARCHAR(255) NOT NULL,
    id_patio BIGINT,
    CONSTRAINT fk_moto_patio FOREIGN KEY (id_patio) REFERENCES T_GEOMOTTU_PATIO(id_patio)
);

INSERT INTO T_GEOMOTTU_MOTO (nr_placa, nr_chassi, tp_modelo, st_operacional, id_patio) VALUES
('BRA1A11', 'CHASSIBR001', 'MOTTUPOP', 'LIVRE', 1),
('BRA2B22', 'CHASSIBR002', 'MOTTUPOP', 'ALUGADA', 1),
('BRA3C33', 'CHASSIBR003', 'MOTTUSPORT', 'MANUTENCAO', 1),
('BRA4D44', 'CHASSIBR004', 'MOTTUE', 'LIVRE', 2),
('BRA5E55', 'CHASSIBR005', 'MOTTUSPORT', 'LIVRE', 3),
('MEX1X11', 'CHASSIMX001', 'MOTTUPOP', 'ALUGADA', 4),
('MEX2Y22', 'CHASSIMX002', 'MOTTUE', 'LIVRE', 4);
